name: nfc_manager_example
description: Demonstrates how to use the nfc_manager plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^3.1.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
